config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :markets, only: [:index, :show]
  resources :vendors, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def app_market_facade
    mf = Rails.cache.read("market_facade")
    # require "byebug"; byebug
    Rails.logger.debug "Cache for market facade?: #{!mf.nil?}"

    if mf.nil?
      mf = MarketFacade.new
      Rails.cache.write("market_facade", mf, expires_in: 48.hours)
    end

    mf
  end
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    # get markets from application controller
    @markets = app_market_facade.markets
  end

  def show
    @market = app_market_facade.market(params[:id])
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def show
    # require "byebug"; byebug
    @vendor = app_market_facade.vendors.find { |vndr| vndr.id == params[:id] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<h1>Markets</h1>
<br>
<table>
  <thead>
      <th>Name</th>
      <th>City</th>
      <th>State</th>
      <th></th>
  </thead>
  <% @markets.each do | market | %>
    <tr id="mrkt-<%= market.id %>">
      <td><%= market.name %></td>
      <td><%= market.city %></td>
      <td><%= market.state %></td>
      <td><%= button_to "More Info", market_path(id: market.id), method: :get %></td>
    </tr>
  <% end %>
</table>

app/views/markets/show.html.erb
<h1><%= @market.name %></h1>
<br>
<h4><%= @market.address %></h4>
<br>
<h5>Vendors at our Market:</h5>
<br>
<% @market.vendors.each do | vendor | %>
  <div><%= link_to "#{vendor.name}", vendor_path(vendor.id), method: :get %></div>
<% end %>

app/views/vendors/show.html.erb
<h1><%= @vendor.name %></h1>
<br>
<h3>Contact Info:</h3>
<h4>Name: <%= @vendor.contact %></h4>
<h4>Phone: <%= @vendor.phone %></h4>
<h3>Credit Accepted?: <%= @vendor.credit_accepted? %></h3>
<h3>Description: <%= @vendor.description %></h3>